[workspace]
members = [
    "argon",
    "argon-slots",
    "argon-tun",
]

[workspace.dependencies]
async-channel = "=1.7.1"
async-trait = "=0.1.67"
clap = "=4.3.2"
futures = "=0.3.28"
packet = "=0.1.4"
thiserror = "=1.0.38"
tokio = "=1.29.1"
tokio-util = "=0.6.10"
tun = "=0.5.5"
