[package]
name = "argon-slots"
version = "0.1.0"
edition = "2021"

[dependencies]
argon = { path = "../argon" }

async-trait = { workspace = true }
packet = { workspace = true }
tokio = { workspace = true }
tun = { workspace = true }
