[package]
name = "argon-slot"
version = "0.1.0"
edition = "2021"

[dependencies]
argon = { path = "../argon" }

async-trait = { workspace = true }
futures = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tun = { workspace = true }