[package]
name = "argon-plugin-registry"
version = "0.1.0"
edition = "2021"

[dependencies]
argon = { path = "../argon" }
argon-plugin = { path = "../argon-plugin" }

libloading = { workspace = true }
thiserror = { workspace = true }
