name: Primary (OB)

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Lint
        run: cargo clippy --all-targets --all-features --
          -D clippy::complexity
          -D clippy::correctness
          -D clippy::perf
          -D clippy::style
          -D clippy::suspicious
