name: Primary (OB)

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Rust Nightly
        run: rustup default nightly && rustup component add rustfmt
      - name: Version
        run: cargo --version
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Format
        run: cargo fmt --all --check --verbose
      - name: Lint
        run: cargo clippy --all-targets --all-features --verbose --
          -D clippy::complexity
          -D clippy::correctness
          -D clippy::pedantic
          -D clippy::perf
          -D clippy::style
          -D clippy::suspicious
          -A clippy::missing_errors_doc
          -A clippy::module_name_repetitions
          -A clippy::must-use-candidate
          -A clippy::return_self_not_must_use
          -A clippy::needless-pass-by-value
